# 01 - Data Understanding & Profiling

## Project
Digital Advertising Campaign Performance Analytics

### Objective

Understand the dataset structure, verify data quality, inspect data types, identify missing values and duplicate records, and assess whether the dataset is suitable for marketing analytics.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display settings
pd.set_option('display.max_columns', None)

In [7]:
df = pd.read_csv("C:/Users/Hp/OneDrive/Desktop/Digital Advertising Campaign Performance Analytics/Data/tech_advertising_campaigns_dataset.csv")

df.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,Curiosity,72,45-54,Female,Shoppers,<$50K,Medium,False,2024-03-06,1,Wednesday,18,34,5,2.23,66329,402,2,896.46,289.67,67.75,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,Neutral,62,65+,Female,Business Professionals,$50K-$100K,Medium,False,2024-01-26,1,Friday,6,22,5,2.48,50094,467,5,1158.16,1728.20,63.73,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,Urgency,79,65+,Male,Tech Enthusiasts,<$50K,High,False,2025-05-15,2,Thursday,1,32,4,3.88,10842,112,6,434.56,2903.26,31.93,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,Joy,57,35-44,All,Shoppers,<$50K,Low,False,2024-07-21,3,Sunday,7,32,4,8.29,7820,123,3,1019.67,502.28,65.52,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,Joy,17,25-34,Female,Students,$100K-$200K,Low,False,2025-03-09,1,Sunday,17,52,7,1.41,21436,302,0,425.82,0.00,68.95,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [16]:
df.tail()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
9995,CAMP_09996,App Installs,Twitter,Sidebar,Mobile,Windows,Story,300x250,Short,False,Curiosity,75,55-64,All,Tech Enthusiasts,<$50K,Medium,False,2026-01-18,1,Sunday,22,55,3,1.90,38819,297,2,564.30,232.68,31.53,139,2.96,E-commerce,High,0.765,1.90,0.673,282.15,0.41,-331.62
9996,CAMP_09997,App Installs,Google Ads,Search,Mobile,iOS,Image,320x50,Short,True,Curiosity,12,25-34,Female,Tech Enthusiasts,$50K-$100K,Medium,False,2025-01-22,1,Wednesday,21,49,6,2.98,16985,405,7,1206.90,3438.01,66.35,74,2.05,Healthcare,Low,2.384,2.98,1.728,172.41,2.85,2231.11
9997,CAMP_09998,Engagement,Facebook,Feed,Desktop,Windows,Image,320x50,Short,True,Trust,6,18-24,Male,Business Professionals,>$200K,Low,False,2024-10-01,4,Tuesday,5,79,4,1.37,25952,621,17,850.77,7126.47,54.86,88,2.17,SaaS,Low,2.393,1.37,2.738,50.05,8.38,6275.70
9998,CAMP_09999,Lead Generation,Facebook,Stories,Mobile,Android,Image,1080x1080,Short,True,Urgency,32,35-44,Male,Tech Enthusiasts,$50K-$100K,Low,True,2025-12-28,4,Sunday,14,5,6,0.62,155858,1776,10,1101.12,4974.42,74.06,110,1.82,SaaS,High,1.139,0.62,0.563,110.11,4.52,3873.30
9999,CAMP_10000,Lead Generation,Google Ads,Feed,Mobile,macOS,Image,1080x1080,Long,False,Urgency,24,45-54,All,Business Professionals,$100K-$200K,Medium,False,2024-08-17,3,Saturday,3,34,5,2.77,270822,2255,26,6246.35,22425.46,66.29,105,3.07,Healthcare,High,0.833,2.77,1.153,240.24,3.59,16179.11

In [22]:
rows, cols = df.shape

print("Number of Rows:", rows)
print("Number of Columns:", cols)

Number of Rows: 10000
Number of Columns: 41

In [17]:
df.sample(5, random_state=42)

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
6252,CAMP_06253,Lead Generation,Google Ads,Sidebar,Mobile,Windows,Image,1920x1080,Medium,True,Fear,1,55-64,Male,Gamers,$50K-$100K,Low,False,2024-09-30,3,Monday,20,44,3,4.75,33668,283,5,1344.25,2118.58,75.16,147,2.97,Education,Medium,0.841,4.75,1.767,268.85,1.58,774.33
4684,CAMP_04685,Conversions,TikTok,Feed,Mobile,Android,Text,728x90,Long,False,Curiosity,77,25-34,Male,Shoppers,$50K-$100K,Medium,True,2024-08-06,3,Tuesday,11,76,3,2.87,270642,957,9,2746.59,1111.67,60.21,41,4.22,E-commerce,Medium,0.354,2.87,0.940,305.18,0.40,-1634.92
1731,CAMP_01732,Conversions,Google Ads,Sidebar,Mobile,iOS,Video,1080x1080,Long,False,Curiosity,77,18-24,Male,Shoppers,>$200K,Medium,False,2024-03-04,1,Monday,6,67,4,3.56,21588,426,7,1516.56,2149.71,56.36,110,4.01,E-commerce,Low,1.973,3.56,1.643,216.65,1.42,633.15
4742,CAMP_04743,Brand Awareness,TikTok,Feed,Desktop,Windows,Carousel,300x250,Long,True,Urgency,5,45-54,Female,Tech Enthusiasts,$100K-$200K,Medium,False,2024-05-12,2,Sunday,1,9,6,1.60,20453,827,17,1323.20,3727.16,38.75,180,1.94,E-commerce,High,4.043,1.60,2.056,77.84,2.82,2403.96
4521,CAMP_04522,Conversions,Instagram,Stories,Mobile,Windows,Interactive,300x250,Short,True,Trust,89,65+,Male,Tech Enthusiasts,$100K-$200K,Medium,False,2025-04-24,2,Thursday,6,11,6,2.92,12994,232,8,677.44,4403.31,53.10,131,2.23,Finance,Low,1.785,2.92,3.448,84.68,6.50,3725.87

# Business Understanding

## Objective

Analyze digital advertising campaign performance to identify
high-performing campaigns, optimize advertising spend,
improve conversion rates, and maximize Return on Ad Spend (ROAS).

## Business Questions

- Which campaigns generate the highest ROI?
- Which platform performs best?
- Which audience converts the most?
- Which device has the highest engagement?
- Which campaigns require optimization?

In [8]:
df.shape

(10000, 41)

In [9]:
df.columns.tolist()

['campaign_id',
 'campaign_objective',
 'platform',
 'ad_placement',
 'device_type',
 'operating_system',
 'creative_format',
 'creative_size',
 'ad_copy_length',
 'has_call_to_action',
 'creative_emotion',
 'creative_age_days',
 'target_audience_age',
 'target_audience_gender',
 'audience_interest_category',
 'income_bracket',
 'purchase_intent_score',
 'retargeting_flag',
 'start_date',
 'quarter',
 'day_of_week',
 'hour_of_day',
 'campaign_day',
 'quality_score',
 'actual_cpc',
 'impressions',
 'clicks',
 'conversions',
 'ad_spend',
 'revenue',
 'bounce_rate',
 'avg_session_duration_seconds',
 'pages_per_session',
 'industry_vertical',
 'budget_tier',
 'CTR',
 'CPC',
 'conversion_rate',
 'CPA',
 'ROAS',
 'profit']

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  str
 1   campaign_objective            10000 non-null  str
 2   platform                      10000 non-null  str
 3   ad_placement                  10000 non-null  str
 4   device_type                   10000 non-null  str
 5   operating_system              10000 non-null  str
 6   creative_format               10000 non-null  str
 7   creative_size                 10000 non-null  str
 8   ad_copy_length                10000 non-null  str
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  str
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  str
 13  target_audience_gender        10000 non-null  str
 14  audience_interest_category    10000 non-null  str
 15  income_bracket                10000 non-null  str
 16  purchase_intent_score         10000 non-null  str
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  str
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  str
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  str
 34  budget_tier                   10000 non-null  str
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
dtypes: bool(2), float64(11), int64(9), str(19)
memory usage: 3.0 MB

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
creative_age_days,10000.0,45.374300,26.171100,1.00,22.0000,45.0000,68.00000,90.00
quarter,10000.0,2.419100,1.132424,1.00,1.0000,2.0000,3.00000,4.00
hour_of_day,10000.0,11.482500,6.932308,0.00,5.0000,12.0000,18.00000,23.00
campaign_day,10000.0,45.429700,26.071107,1.00,23.0000,45.0000,68.00000,90.00
quality_score,10000.0,5.527400,1.553541,1.00,4.0000,6.0000,7.00000,10.00
actual_cpc,10000.0,3.290336,2.453852,0.30,1.5100,2.4300,4.53000,16.03
impressions,10000.0,70539.223000,91339.733246,5000.00,16958.5000,37469.5000,83213.75000,500000.00
clicks,10000.0,1526.436100,2412.164582,10.00,290.0000,718.0000,1746.00000,40000.00
conversions,10000.0,65.568800,183.404876,0.00,5.0000,16.0000,55.00000,5384.00
ad_spend,10000.0,4345.566179,6917.481037,8.69,666.3075,1895.6700,4996.16000,49999.68
revenue,10000.0,28415.770647,89284.609131,0.00,1608.9100,6099.2400,22165.82500,2800397.43
bounce_rate,10000.0,52.528500,17.706165,10.00,40.0875,53.5800,65.47250,90.00
avg_session_duration_seconds,10000.0,100.956600,46.541295,10.00,68.0000,100.0000,132.00000,277.00
pages_per_session,10000.0,3.113223,1.369884,1.00,2.1600,2.8300,3.74000,8.51
CTR,10000.0,2.314340,1.573316,0.10,1.1720,1.9200,3.01725,8.00
CPC,10000.0,3.290336,2.453852,0.30,1.5100,2.4300,4.53000,16.03
conversion_rate,10000.0,3.644033,4.354338,0.00,1.0050,2.1655,4.49325,25.00
CPA,10000.0,190.895894,295.614462,0.00,40.6400,99.4600,225.45750,6379.94
ROAS,10000.0,7.524918,14.985237,0.00,1.1975,3.1500,7.95000,487.30
profit,10000.0,24070.204468,86416.098554,-36939.84,209.4800,3302.5350,16641.87750,2750397.93

In [12]:
df.isnull().sum()

campaign_id                     0
campaign_objective              0
platform                        0
ad_placement                    0
device_type                     0
operating_system                0
creative_format                 0
creative_size                   0
ad_copy_length                  0
has_call_to_action              0
creative_emotion                0
creative_age_days               0
target_audience_age             0
target_audience_gender          0
audience_interest_category      0
income_bracket                  0
purchase_intent_score           0
retargeting_flag                0
start_date                      0
quarter                         0
day_of_week                     0
hour_of_day                     0
campaign_day                    0
quality_score                   0
actual_cpc                      0
impressions                     0
clicks                          0
conversions                     0
ad_spend                        0
revenue                         0
bounce_rate                     0
avg_session_duration_seconds    0
pages_per_session               0
industry_vertical               0
budget_tier                     0
CTR                             0
CPC                             0
conversion_rate                 0
CPA                             0
ROAS                            0
profit                          0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.dtypes

campaign_id                         str
campaign_objective                  str
platform                            str
ad_placement                        str
device_type                         str
operating_system                    str
creative_format                     str
creative_size                       str
ad_copy_length                      str
has_call_to_action                 bool
creative_emotion                    str
creative_age_days                 int64
target_audience_age                 str
target_audience_gender              str
audience_interest_category          str
income_bracket                      str
purchase_intent_score               str
retargeting_flag                   bool
start_date                          str
quarter                           int64
day_of_week                         str
hour_of_day                       int64
campaign_day                      int64
quality_score                     int64
actual_cpc                      float64
impressions                       int64
clicks                            int64
conversions                       int64
ad_spend                        float64
revenue                         float64
bounce_rate                     float64
avg_session_duration_seconds      int64
pages_per_session               float64
industry_vertical                   str
budget_tier                         str
CTR                             float64
CPC                             float64
conversion_rate                 float64
CPA                             float64
ROAS                            float64
profit                          float64
dtype: object

In [15]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"{col}: {df[col].nunique()} unique values")

campaign_id: 10000 unique values
campaign_objective: 5 unique values
platform: 6 unique values
ad_placement: 6 unique values
device_type: 3 unique values
operating_system: 5 unique values
creative_format: 6 unique values
creative_size: 6 unique values
ad_copy_length: 3 unique values
creative_emotion: 6 unique values
target_audience_age: 6 unique values
target_audience_gender: 3 unique values
audience_interest_category: 6 unique values
income_bracket: 4 unique values
purchase_intent_score: 3 unique values
start_date: 761 unique values
day_of_week: 7 unique values
industry_vertical: 6 unique values
budget_tier: 3 unique values

C:\Users\Hp\AppData\Local\Temp\ipykernel_19080\1263483761.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns

In [21]:
numerical_columns = df.select_dtypes(include=np.number).columns

categorical_columns = df.select_dtypes(exclude=np.number).columns

print("Numerical Columns:", len(numerical_columns))
print("Categorical Columns:", len(categorical_columns))

Numerical Columns: 20
Categorical Columns: 21

In [18]:
df.memory_usage(deep=True)

Index                              132
campaign_id                     590000
campaign_objective              622468
platform                        573241
ad_placement                    563084
device_type                     553556
operating_system                545840
creative_format                 548056
creative_size                   567840
ad_copy_length                  542088
has_call_to_action               10000
creative_emotion                545692
creative_age_days                80000
target_audience_age             539206
target_audience_gender          534123
audience_interest_category      628076
income_bracket                  576009
purchase_intent_score           536006
retargeting_flag                 10000
start_date                      590000
quarter                          80000
day_of_week                     561512
hour_of_day                      80000
campaign_day                     80000
quality_score                    80000
actual_cpc                       80000
impressions                      80000
clicks                           80000
conversions                      80000
ad_spend                         80000
revenue                          80000
bounce_rate                      80000
avg_session_duration_seconds     80000
pages_per_session                80000
industry_vertical               567790
budget_tier                     535462
CTR                              80000
CPC                              80000
conversion_rate                  80000
CPA                              80000
ROAS                             80000
profit                           80000
dtype: int64

In [20]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(11.768513679504395)

# Initial Findings

- Dataset contains 10,000 campaign records.
- Contains 41 variables.
- Missing values: 0
- Duplicate records: 0
- Dataset appears suitable for marketing analytics.
- Multiple campaign platforms are available.
- Includes financial KPIs such as ROAS, CPC, CPA, Revenue and Profit.

# Conclusion

The dataset has been successfully profiled and validated.

### Key Observations

- The dataset contains 10,000 campaign records across 41 variables.
- No missing values were identified.
- No duplicate records were found.
- Numerical and categorical variables are well structured.
- The dataset includes campaign, customer, financial, and engagement metrics.
- Overall, the dataset is suitable for marketing analytics and business intelligence reporting.

The next step is Data Cleaning & Preprocessing to validate data consistency and prepare the dataset for exploratory analysis.